[RP_connection]
sim               = "False"
super_sim         = "True"
super_sim_fr      = 1
baud_rate         = 115200
device_ID         = ""
fake_device_ID    = ""
time_out          = 1       
read_time         = 0.5    
hb_send_msg       = "ping"
hb_receive_msg    = "pong"
retries           = 3
connection_cycles = 2
power_cycles      = 3


[solenoid]
channel = 6
time    = 150

[servo]
channel    = 4
on_clicks  = 1900
off_clicks = 500
time       = 500

[purple_lights]
channel = 2
g       = 0
r       = 100
b       = 100
w       = 100

[white_lights]
channel = 2
g       = 0
r       = 0
b       = 0
w       = 100





